apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app2=docker.io/rajarammurali513/app2:~1
    argocd-image-updater.argoproj.io/app2.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app2.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/charts/app2/values.yaml
    argocd-image-updater.argoproj.io/app1.pull-secret: secret:argocd/regcred
spec:
  project: default
  source:
    repoURL: https://github.com/rajaramiotfal/sample-argocd-helm.git
    targetRevision: main
    path: charts/app2
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
