replicaCount: 1
image:
  repository: docker.io/rajarammurali513/app1:~1
  tag: "1.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
containerPort: 8080
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: app1.localtest.me
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
